<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Jan.29th, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog UserModel类文件
 *		
 *		本文件用于配置User模型
 */

class SiteModel extends Model{
	
	function __construct(){
		parent::__construct();
	}
	
	function siteModel_getSiteInfo(){
		$sql = '';
		$sql = 'SELECT * FROM blog_siteinfo';
		$result = $this->pdodbh->db_query($sql);
		
		return $result;
	}
	
	function siteModel_editSiteInfo($mode = null, $params = array()){
		$sql = '';
		$result = null;
		
		switch($mode){
			case 'insert':
				$keys = '';
				$values = '';
				foreach($params as $key=>$value){
					if(isset($value)){
						if($values !== ''){
							$keys = $keys.', ';
							$values = $values.', ';
						}
						$keys = $keys.$key;
						$values = $values.'\''.$value.'\'';
					}
				}
				$sql = 'INSERT INTO blog_siteinfo ('.$keys.') VALUES ('.$values.')';
				$result = $this->pdodbh->db_insert($sql);
				//var_dump($sql);
				//var_dump($result);
				break;
			case 'update':
				foreach($params as $key=>$value){
					if(isset($value)){
						if($sql !== ''){
							$sql = $sql.', ';
						}
						$sql = $sql.$key.' = \''.$value.'\'';
					}
				}
				$sql = 'UPDATE blog_siteinfo SET '.$sql;
				$result = $this->pdodbh->db_update($sql);
				break;
			default:
				return false;
		}
		
		return $result;
	}
}

?>