<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Jan.30th, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog 路由分发及入口文件
 *		
 *		本文件用于url寻址分发，同时作为站点入口，
 *		所有访问本站的地址将会统一至此进行处理
 */

require_once(str_replace('\\', '/', dirname(__FILE__)).'/config/global.config.php');

$pos = $_SERVER['PHP_SELF'];
define('WEBDIR', str_replace('dispatch.php', '', $pos));

if(INSTALL_ACCOMPLISH == false){
	$url = WEBDIR.'install.php';
	header('refresh:0;url='.$url);
}else{
	if(file_exists(WEBROOT.'controller/'.$controller.'.controller.php')){
		include_once(WEBROOT.'controller/'.$controller.'.controller.php');
		$controller_name = (ucfirst($controller)).'Controller';

		$controller_instance = new $controller_name();
		$controller_instance->$action();
	}else{
		header('Location:article/index');
	}
}


#unit_test
//var_dump($controller_name);
//var_dump($action);
?>