<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Jan.27th, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog数据库基础配置文件
 *		
 *		本文件用于存储用户关于数据库相关配置
 *		以启动之后对于数据库的安装、配置等操作
 */
 
//数据库产品类型配置
define('PDO_DB_TYPE', 'mysql');

//数据库登录主机配置
define('PDO_DB_HOST', 'localhost');

//数据库名称配置
define('PDO_DB_NAME', 'miaoblog');

//数据库登录用户配置
define('PDO_DB_USER', 'MiaoBlog');

//数据库登录密码配置
define('PDO_DB_PASSWORD', 'hy123');


?>