<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Jan.28th, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog全局配置文件
 *		
 *		本文件用于设置框架全局配置
 */

define('INSTALL_ACCOMPLISH', true);
define('ARTICLE_AMOUNT_PERPAGE', 2);

define('WEBROOT', str_replace('\\', '/', dirname(dirname(__FILE__))).'/');
define('TIMEZONE', 'Asia/Shanghai');


require_once(WEBROOT.'config/'.'db.config.php');
require_once(WEBROOT.'config/'.'routes.config.php');

require_once(WEBROOT.'class/'.'db.class.php');
require_once(WEBROOT.'class/'.'model.class.php');
require_once(WEBROOT.'class/'.'controller.class.php');
require_once(WEBROOT.'class/'.'view.class.php');

require_once(WEBROOT.'model/'.'user.model.php');
require_once(WEBROOT.'model/'.'article.model.php');
require_once(WEBROOT.'model/'.'manage.model.php');
require_once(WEBROOT.'model/'.'site.model.php');

date_default_timezone_set(TIMEZONE);

session_start();
header('Content-Type: text/html; charset=utf-8');

//require_once('')
//var_dump(WEBROOT);
?>