<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Feb.1st, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog ArticleController类文件
 *		
 *		本文件用于配置ArticleController及其相关action
 */
class ArticleController extends Controller{
	private $article = null;
	private $categroy_info = null;
	private $login_user_info = null;
	private $login_site_info = null;
	
	function __construct(){
		parent::__construct(__CLASS__);
		$this->article = $this->model;
		
		$login_site = new SiteModel();
		$this->login_site_info = $login_site->siteModel_getSiteInfo();
		$this->login_site_info = $this->login_site_info[0];
		$this->view->login_site_info = $this->login_site_info;
		
		if($this->checkSession()){
			$login_user = new UserModel();
			$this->login_user_info = $login_user->userModel_getUserInfo();
			$this->login_user_info = $this->login_user_info[0]; 
			$login_user_info = $this->login_user_info;
			$this->view->login_user_info = $login_user_info;
		}
		
		$this->category_info = $this->article->articleModel_queryCategoryInfo();
		$this->view->category_info = $this->category_info;
	}
	
	function index(){
		$array_info = $this->getInfo($_SERVER['QUERY_STRING']);
		if((!isset($array_info['page']))||($array_info['page'] == '')){
			$array_info['page'] = 1;
		}
		$article_tmp = $this->article->articleModel_getArticleInfo('all', array());
		$page = $array_info['page'];
		if($page > (ceil(count($article_tmp) / ARTICLE_AMOUNT_PERPAGE))){
			$article_view = null;
			$this->view->article = $article_view;
			$this->view->article_amount = count($article_tmp);
			$this->view->display(__CLASS__, __FUNCTION__);
			return ;
		}
		$start_index = ($page - 1) * ARTICLE_AMOUNT_PERPAGE;
		$end_index = $page * ARTICLE_AMOUNT_PERPAGE - 1;
		$i = $start_index;
		$article_view = array();
		for($i, $j = 0;$i <= $end_index;$i ++, $j ++){
			if(!isset($article_tmp[$i]))
				break;
			if((!isset($article_tmp[$i]['summary']))||($article_tmp[$i]['summary'] === '')){
				$article_tmp[$i]['summary'] = $article_tmp[$i]['content'];
			}
			$article_tmp[$i]['categoryinfo'] = $this->handleArticleCategory($article_tmp[$i]['categoryid']);
			$article_view[$j] = $article_tmp[$i];
			//var_dump($article_view[$j]['articleid']);
		}
		$this->view->article = $article_view;
		$this->view->article_amount = count($article_tmp);
		
		$this->view->display(__CLASS__, 'index');
	}
	
	/**
	 *		MiaoBlog ArticleController::categoryInfo()函数
	 *		
	 *		用于查询用户的文章分类情况
	 */
	function categoryInfo(){
		$category_info = $this->category_info;
		if(!isset($category_info)){
			header('Location:../error/error_authornotexists.html');
		}
		$category_count = count($category_info);
		$this->view->page_amount = ceil($category_count / CATEGORY_AMOUNT_PERPAGE);
		$this->view->display(__CLASS__, __FUNCTION__);
	}
	
	/**
	 *		MiaoBlog ArticleController::categoryDetail()函数
	 *		
	 *		用于查询指定用户的指定文章分类下的全部文章	
	 */
	function categoryDetail(){
		$array_info = $this->getInfo($_SERVER['QUERY_STRING']);
		if(!isset($array_info['categoryid'])){
			header('Location:index');
		}
		if((!isset($array_info['page']))||($array_info['page'] == '')){
			$array_info['page'] = 1;
		}
		$category_article = $this->article->articleModel_queryCategoryArticle($array_info['categoryid']);
		$this->view->category_id = $array_info['categoryid'];
		$article_amount = count($category_article);
		$page_amount = ceil($article_amount / ARTICLE_AMOUNT_PERPAGE);
		$page = $array_info['page'];
		if($page > $page_amount){
			$category_view = null;
			$this->view->page_amount = $page_amount;
			$this->view->category_article = $category_view;
			$this->view->display(__CLASS__, __FUNCTION__);
			return ;
		}
		$start_index = ($page - 1) * ARTICLE_AMOUNT_PERPAGE;
		$end_index = $page * ARTICLE_AMOUNT_PERPAGE - 1;
		$i = $start_index;
		$article_view = array();
		for($i, $j = 0;$i <= $end_index;$i ++, $j ++){
			if(!isset($category_article[$i]))
				break;
			if((!isset($category_article[$i]['summary']))||($category_article[$i]['summary'] === '')){
				$category_article[$i]['summary'] = $category_article[$i]['content'];
			}
			$category_article[$i]['categoryinfo'] = $this->handleArticleCategory($category_article[$i]['categoryid']);
			$category_view[$j] = $category_article[$i];
			//var_dump($article_view[$j]['articleid']);
		}
		//var_dump($category_article);
		if(!isset($category_article)){
			header('Location:../error/error_categorynotexists.html');
		}
		$this->view->page_amount = $page_amount;
		$this->view->category_article = $category_view;
		$this->view->display(__CLASS__, __FUNCTION__);
	}
	
	/**
	 *		MiaoBlog ArticleController::articleDetail()函数
	 *		
	 *		用于查询指定用户的指定文章的相关内容	
	 */
	function articleDetail(){
		$array_info = $this->getInfo($_SERVER['QUERY_STRING']);
		if(!isset($array_info)){
			header("Location:index");
		}
		if(!isset($array_info['articleid'])){
			if(isset($array_info['authorid'])){
				header("Location:index?".$_SERVER['QUERY_STRING']);
			}else{
				header('Location:index');
			}
		}
		//$article_detail = $this->article->articleModel_queryArticle(array('articleid'=>(int)$array_info['articleid'], 'authorid'=>$array_info['authorid']),array('*'));
		$article_detail = $this->article->articleModel_queryArticle(array('articleid'=>(int)$array_info['articleid']),array('*'));
		if((empty($article_detail))||(!isset($article_detail))){
			//header('Location:'.WEBROOT.'error/error_articlenotexists.html');
			header('Location:../error/error_articlenotexists.html');
		}
		$article_detail = $article_detail[0];
		$article_detail['categoryinfo'] = $this->handleArticleCategory($article_detail['categoryid']);
		$this->view->article_detail = $article_detail;
		$this->view->display(__CLASS__, __FUNCTION__);
	}
	
	function about(){
		$this->view->display(__CLASS__, __FUNCTION__);
	}
	
	/**
	 *		MiaoBlog ArticleController::getInfo()函数
	 *		
	 *		用于获取QUERY_STRING中内容，功能近似于$_GET
	 *		以数组形式返回
	 */
	function getInfo($query_string){
		if(($query_string === '')||(!isset($query_string))){
			return null;
		}
		$get_info_tmp = explode('&', $query_string);
		$get_info = array();
		foreach($get_info_tmp as $value){
			if(!strstr($value, '=')){
				continue;
			}
			list($get, $info) = split('=', $value);
			$get_info[$get] = $info;
		}
		
		return $get_info;
	}
	
	function checkSession(){
		if(isset($_SESSION['username'])){
			return true;
		}else{
			return false;
		}
	}
	
	function handleArticleCategory($categoryid){
		if($categoryid == 1){
			$categoryname = '未分类';
		}else{
			$categoryinfo = $this->article->articleModel_queryOneCategory($categoryid);
			$categoryname = $categoryinfo[0]['categoryname'];
		}
		return $categoryname;
	}
}


?>