<?php
/**
 *		MiaoBlog OpenSource Web Frame
 *		PoweredBy PlanetMiao  &&  DesignedBy hyMiao@PlanetMiaoTeam
 * 		Version: 0.0.0 Beta
 * 		Generated By hyMiao on Jan.30th, 2013
 *		More info: http://www.planetMiao.com
 */
 
/**
 *		MiaoBlog UserController类文件
 *		
 *		本文件用于配置UserController以及其相关action
 */
//require_once('../config/global.config.php');
 
class UserController extends Controller{
	private $user = null;
	
	function __construct(){
		parent::__construct(__CLASS__);
		$this->user = $this->model;
	}
	
	public function index(){
		$this->view->msg='';
		if(!isset($_SESSION['username'])){
			$this->view->display(__CLASS__, __FUNCTION__);
		}else{
			header('Location:../article/index');
		}
	}
	
	public function doLogin(){
		$username = $_POST['username'];
		$password = md5($_POST['password']);
		
		$check_array = $this->user->userModel_getUserInfo();
		if((isset($check_array)) && (!empty($check_array))){
			$user_info = $check_array[0];
		}
		if($user_info['username'] != $username){
			//$this->view->msg='usernotexists';
			print 0;
		}else if($user_info['pwd'] !== $password){
			//$this->view->msg='passwordwrong';
			print 1;
		}else{
			$_SESSION['username']=$username;
			$this->user->userModel_changeInfo('sys', array('last_access_ip'=>$_SERVER['REMOTE_ADDR']));
			print 2;
		}
	}
	
	public function doLogout(){
		var_dump($_SESSION['username']);
		session_destroy();
		header('Location:../article/index');
	}
}

$usertest = new UserController();

?>